RegisterCommand('weather', function()
    SendNUI('openUI', true)
    SetNuiFocus(true, true)
    SendNUI('getTime',GetClockHours())
end, false)
RegisterCommand('weather:random', function()
    SetRandomWeatherType()
end, false)

RegisterNUICallback('setWeather', function(data,cb)
    SetOverrideWeather(data)
end)
RegisterNUICallback('setTime', function(data,cb)
    NetworkOverrideClockTime(tonumber(data), 5, 5)
end)
RegisterNUICallback('close', function(_, cb)
    cb({})
    SetNuiFocus(false, false)
end)
